spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test;MODE=MySQL
    username: sa
    password:
#  jpa:
#    show_sql: true
#    hibernate:
#      ddl-auto: create